apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: notes-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-web
  template:
    metadata:
      labels:
        app: notes-web
    spec:
      containers:
        - name: web
          image: notes-web:1.0.0
          ports:
            - containerPort: 8080
